name: Feature request
description: Propose a new feature or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: I want to compare spending between my ward and city-wide totals...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like to see?
      description: Describe the view, metric, or workflow.
      placeholder: Add a toggle to view ward-level spending alongside city-wide totals.
    validations:
      required: true
  - type: textarea
    id: data
    attributes:
      label: Data or references
      description: Datasets, URLs, or examples that would inform the feature.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: If you tried other approaches, note them here.
    validations:
      required: false
  - type: textarea
    id: impact
    attributes:
      label: Who benefits?
      description: Describe the audiences or use cases.
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      description: Mockups, sketches, or other context.
    validations:
      required: false
